/**
 * PR comment builder for TestivAI visual reports
 */

import { ResultsData, SnapshotResult } from './types';

const UPSERT_MARKER = '<!-- testivai-visual-report -->';

/**
 * Build markdown PR comment from results
 */
export function buildComment(results: ResultsData): string {
  const { summary, snapshots } = results;

  // Header with emoji summary
  const passedEmoji = summary.passed > 0 ? '✅' : '⬜';
  const changedEmoji = summary.changed > 0 ? '⚠️' : '⬜';
  const newEmoji = summary.newSnapshots > 0 ? '🆕' : '⬜';

  const summaryLine = `${passedEmoji} **${summary.passed} passed** · ${changedEmoji} **${summary.changed} changed** · ${newEmoji} **${summary.newSnapshots} new**`;

  let comment = `${UPSERT_MARKER}

### 🔍 TestivAI Visual Report

${summaryLine}

**Total snapshots:** ${summary.total}

`;

  // Show changed snapshots with approve command
  const changedSnapshots = snapshots.filter(s => s.status === 'changed');
  if (changedSnapshots.length > 0) {
    comment += '#### Changed Snapshots\n\n';
    for (const snapshot of changedSnapshots) {
      const diffPercent = snapshot.diffPercentage?.toFixed(2) || '0.00';
      comment += `<details>
<summary><code>${snapshot.name}</code> — ${diffPercent}% different</summary>

\`\`\`bash
npx testivai approve "${snapshot.name}"
# Or approve all changed snapshots:
npx testivai approve --all
\`\`\`
</details>

`;
    }
  }

  // Show new snapshots
  const newSnapshots = snapshots.filter(s => s.status === 'new');
  if (newSnapshots.length > 0) {
    comment += '#### New Snapshots\n\n';
    for (const snapshot of newSnapshots) {
      comment += `- \`${snapshot.name}\`\n`;
    }
    comment += '\n';
  }

  // Footer with report link
  comment += '---\n*Generated by [TestivAI](https://testiv.ai)*\n';

  return comment;
}

/**
 * Build simple message for empty results
 */
export function buildEmptyComment(): string {
  return `${UPSERT_MARKER}

### 🔍 TestivAI Visual Report

No visual snapshots were captured in this test run.

---
*Generated by [TestivAI](https://testiv.ai)*
`;
}
